### ISSUE TITLE
Zamiana imion na obiekty reprezentujące pracowników

### ISSUE THREAD

**Issue by sdwsk** [TomekMoryl/32#3]
Stwórz nowego brancha na to zadanie - nazwij go po angielsku, z podłogami zamiast spacji oraz wybierz nazwę najlepiej oddającą po co on jest.

Stwórz klasę odpowiadającą pracownikowi. Przyjmijmy narazie, że każdy pracownik ma imię, wiek i określoną pensję. Przyjmijmy że pensja jest liczbą naturalną.

Zainicjalizuj listę w konstruktorze kilkoma takimi obiektami. W metodzie main wypisz pracowników na ekran.

**Comment by TomekMoryl** [comment]
Tutaj jest pull request tego zadania https://github.com/TomekMoryl/32/pull/5
Mam nadzieję, że o to chodziło rozbiłem to na 3 klasy 
1) Zawiera tylko klasę dla pracowników 
2) Zawiera konstruktor dodający pracownika i wyświetlający Imię, wiek i pensję
3) metoda main wywołuje instancję konstruktora i wyświetla tekst.

Zresztą co ja ci piszę i tak widzisz co zrobiłem. 
Największy problem stwarza mi nazewnictwo nie chodzi o angielski a raczej o pewną konwencję czy nazywaniu nie wiem czy czasami zrobić metodę printInfo czy showEmplyees, to bardziej robi się na wyczucie czy z doświadczeniem i przeglądaniem kodów po prostu automatycznie nazywa się elementy ?

**Comment by sdwsk** [comment]
Trochę chaosu wkradło mi się do komentarzy, bo rozbiłeś to trochę za bardzo. Jeśli chciałbyś mieć 3 klasy - to jedna, będzie opisywać pracownika, druga, opisywać będzie sklep i będzie ona posiadać w sobie pole z listą pracowników i 3 będzie to klasa z metodą main, która staje się tak jakby demem Twojej aplikacji.

**Comment by sdwsk** [comment]
Popatrz na to z życia strony - masz pracowników, których dodajesz do sklepu, a następnie chcesz wyświetlić kto dla tego sklepu pracuje. Narazie chciałbym żeby pracownicy dodawali się wraz ze stworzeniem sklepu - lista ma inicjalizować się w konstruktorze sklepu.
